image:
  tag: "0.813.1"

service:
  type: ClusterIP
  port: "8080"

postgresql:
  enabled: false
  existingSecret: "lightdash-db-credentials"

## External PostgreSQL configuration
## All of these values are only used when postgresql.enabled is set to false
## @param externalDatabase.host Database host
## @param externalDatabase.user non-root Username for Lightdash Database
## @param externalDatabase.password Database password
## @param externalDatabase.existingSecret Name of an existing secret resource containing the DB password
## @param externalDatabase.existingSecretPasswordKey Name of an existing secret key containing the DB password
## @param externalDatabase.database Database name
## @param externalDatabase.port Database port number
##
externalDatabase:
  host: "10.100.0.3"
  user: "lightdash-root"
  existingSecret: "lightdash-db-credentials"
  secretKeys:
    passwordKey: "password"
  database: lightdash
  port: 5432

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: "cloud.google.com/gke-nodepool"
              operator: In
              values:
                - mds

resources:
  limits:
    cpu: 300m
    memory: 512Mi
  requests:
    cpu: 150m
    memory: 256Mi
    
replicaCount: 0
autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
#    targetMemoryUtilizationPercentage: 80

browserless-chrome:
  enabled: true # should be disabled but a bug https://github.com/lightdash/helm-charts/issues/46 prevents to generate the manifests
  replicaCount: 0