apiVersion: v1
name: istiod
# This version is never actually shipped. istio/release-builder will replace it at build-time
# with the appropriate version
version: 1.0.0
appVersion: 1.0.0
tillerVersion: ">=2.7.2"
description: Helm chart for istio control plane
keywords:
  - istio
  - istiod
  - istio-discovery
icon: https://istio.io/latest/favicons/android-192x192.png
dependencies:
  - name: istiod
    version: 1.14.1
    repository: https://istio-release.storage.googleapis.com/charts
